/** 
  ******************************************************************************
  * @file    JIG_TEST_param_gimbal.h
  * @author  Gremsy Team
  * @version v2.0.1
  * @date    2021
  * @brief   This file contains all the functions prototypes for the  
  *          firmware library.
  *
  ******************************************************************************
  * @Copyright
  * COPYRIGHT NOTICE: (c) 2021 Gremsy. All rights reserved.
  *
  * The information contained herein is confidential
  * property of Company. The use, copying, transfer or 
  * disclosure of such information is prohibited except
  * by express written agreement with Company.
  *
  ******************************************************************************
*/

/* Define to prevent recursive inclusion -------------------------------------*/

#ifndef __JIG_TEST_PARAM_GIMBAL_H
#define __JIG_TEST_PARAM_GIMBAL_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/

#include "stdio.h"
#include "stdlib.h"
#include "stdbool.h"
#include "stdint.h"
/* Exported define ------------------------------------------------------------*/
#define JIG_TEST_NUMBER_OF_PARAM_SETTING            36
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP           44

#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000   56

#define JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN          6
#define JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN         1
#define JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN          7
#define JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN           0
#define JIG_TEST_SETTING_PARAM_TEST_YAW_D                   2
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_D                 2
#define JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW              40
#define JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL             40
#define JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH            40

#define JIG_TEST_SETTING_PARAM_TEST_YAW_P_PIXY              60
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_P_PIXY             50
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_P_PIXY            50

#define JIG_TEST_SETTING_PARAM_TEST_YAW_P_T3V3              90
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_P_T3V3             80
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_P_T3V3            70

#define JIG_TEST_SETTING_PARAM_TEST_YAW_P_S1V3              60
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_P_S1V3             50
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_P_S1V3            45
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER_S1V3        30
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER_S1V3         40
#define JIG_TEST_SETTING_PARAM_TEST_YAW_POWER_S1V3          40

#define JIG_TEST_SETTING_PARAM_TEST_YAW_P_T7                70
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_P_T7               60
#define JIG_TEST_SETTING_PARAM_TEST_PITCH_P_T7              50

#define JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER             40
#define JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER              40
#define JIG_TEST_SETTING_PARAM_TEST_YAW_POWER               40
#define JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS                16
#define JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED          60
#define JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED           60
#define JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED            60

#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T3V3_BMI       2
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T3V3_ICM       4
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_S1V3_BMI       2
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_S1V3_ICM       2
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T7_BMI         2
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T7_ICM         8

#define JIG_TEST_SETTING_PARAM_TEST_YAW_I                   4 /// Output filtter
#define JIG_TEST_SETTING_PARAM_TEST_YAW_I_S1V3              4
#define JIG_TEST_SETTING_PARAM_TEST_YAW_I_T7                8

#define JIG_TEST_SETTING_PARAM_TEST_PITCH_I                 120
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST              220
#define JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST_S1V3         210
#define JIG_TEST_SETTING_PARAM_TEST_IMU_RATE                15
#define JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT          1
#define JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE             10
#define JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE            10
#define JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE              10

#define JIG_TEST_SETTING_PARAM_TEST_ACSL_ROTATION_TRAVEL_MIN_PIT           -90/// Rotation TILT Up
#define JIG_TEST_SETTING_PARAM_TEST_ACSL_ROTATION_TRAVEL_MAX_PIT           30/// Rotation TILT Down

#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PIT           -90/// Rotation TILT Up
#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PIT           90/// Rotation TILT Down
#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_ROLL          -80/// Rotation ROLL Up
#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_ROLL          80/// Rotation ROLL Down
#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PAN           -180/// Rotation PAN Up
#define JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PAN           180/// Rotation PAN Down

#define JIG_TEST_GIMBAL_USER_PROFILE_T3V3_STIFFNESS_DIR_MOTOR_ROLL         0 /// Auto Power ON

#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_P            25
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_P             25
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_P              25
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_I              4
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_GYRO_LPF           4
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_POWER        40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_POWER         40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_POWER          40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_I            120
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_DIR_MOTOR_ROLL     0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_FOLLOW       100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_FILTER       50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_TILT_WINDOW        5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_D             1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_FOLLOW         100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_FILTER         50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PAN_WINDOW         5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_DIR_MOTOR_PITCH    0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_GYRO_TRUST         210
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_TRIM      0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_TRIM       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_MODE_CHAN     5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_PITCH_CHAN    1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_LPF       50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_MODE      1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_ROLL_CHAN     9
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_LPF        50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_MODE       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_YAW_CHAN      3
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_YAW_LPF         60
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_YAW_MODE        1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_D            4
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_D              4

#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MODE_SETTING_ROLL_FILTER      0 /// Mapping Angle
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MODE_SETTING_JOY_AXIS        (uint8_t)0x10//0b00010000
    /* 0x00ABCDEF
    A :Reduced Drift by DRONE Roll & Tilt Axis DISABLE
    B :Reduced Drift by DRONE Pan Axis ENABLE
    C :Home return DISABLE
    D : CONTROL - ROLL - NOMAL
    E : CONTROL - PAN  - NOMAL
    F : CONTROL - TILT - NOMAL
        
    */
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_P                 70 /// Stiffness Basic TILT
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_ROLL_P                  80 /// Stiffness Basic ROLL
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_P                   90 /// Stiffness Basic PAN
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_I                   4  /// Output Filter
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_GYRO_LPF                2  /// Gyro Filter
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_POWER             40 /// Stiffness Expert HOLD STRENGTH TILT
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_ROLL_POWER              40 /// Stiffness Expert HOLD STRENGTH ROLL
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_POWER               40 /// Stiffness Expert HOLD STRENGTH PAN
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_I                 120 /// Gain
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_DIR_MOTOR_ROLL          0  /// Auto Power ON
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_PITCH_FOLLOW          180 /// Follow tilt Speed
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_PITCH_FILTER          0 /// Follow tilt Smooth
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_TILT_WINDOW           0 /// Follow tilt window
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_ROLL_D                0 /// Follow tilt TILT LOCK
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_YAW_FOLLOW             180 /// Follow pan Speed
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_YAW_FILTER             0 /// Follow pan Smooth
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_PAN_WINDOW             0 /// Follow pan window
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_DIR_MOTOR_PITCH        0 /// Follow pan Airborne OFF
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_PITCH_SPEED            50/// Control TILT Speed
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_ROLL_SPEED             180/// Control ROLL Speed
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_YAW_SPEED              50/// Control PAN  Speed
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_PITCH_LPF              10/// Control TILT Smooth
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_ROLL_LPF               0/// Control ROLL Smooth
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_YAW_LPF                10/// Control PAN Smooth
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RADIO_TYPE                15  /// Control mavlink
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_HEARTBEAT_EMIT   1 /// mavlink msg rate heartbeat
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_STATUS_RATE      10 /// mavlink msg rate status
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_ENC_CNT_RATE     50 /// mavlink msg rate encoder
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_ORIEN_RATE       30 /// mavlink msg rate encoder
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_IMU_RATE         10 /// mavlink msg rate encoder
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_ENC_TYPE_SEND             0 // Encoder Type send
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_IMU_GYRO_TRUST                    210 /// Gyro truct
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_SKIP_GYRO_CALIB                   0 /// Calib gyro at startup
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CAN_LINK_RC_PITCH_TRIM            0 /// Canlink tilt Offset
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CAN_LINK_RC_ROLL_TRIM             0 /// Canlink roll Offset
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_PIT           -90/// Rotation TILT Up
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_PIT           90/// Rotation TILT Down
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_ROLL          -45/// Rotation ROLL Up
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_ROLL          45 /// Rotation ROLL Down
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_PAN           -320/// Rotation PAN Up
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_PAN           320/// Rotation PAN Down
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRIM_HOZ                 0/// Rotation ROLL Offset
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MOTOR_ROLL_FOLLOW                 0/// Motor home 
// 45

#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_P            40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_P             40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_P              50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_I              3
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_GYRO_LPF           4
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_POWER        30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_POWER         30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_POWER          35
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_I            120
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_DIR_MOTOR_ROLL     0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_FOLLOW       100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_FILTER       50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_TILT_WINDOW        5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_D             0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_FOLLOW         100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_FILTER         50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PAN_WINDOW         5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_DIR_MOTOR_PITCH    0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_GYRO_TRUST         220
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_TRIM      0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_TRIM       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_MODE_CHAN     6
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_PITCH_CHAN    1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_LPF       30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_MODE      1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_ROLL_CHAN     9
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_LPF        30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_MODE       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_YAW_CHAN      3
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_YAW_LPF         30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_YAW_MODE        1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_D            2
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_D              2

#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_P            40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_P             40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_P              40
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_I              4
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_GYRO_LPF           2
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_POWER        30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_POWER         30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_POWER          30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_I            120
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_DIR_MOTOR_ROLL     0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_FOLLOW       100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_FILTER       50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_TILT_WINDOW        5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_D             0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_FOLLOW         100
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_FILTER         50
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PAN_WINDOW         5
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_DIR_MOTOR_PITCH    0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_GYRO_TRUST         220
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_TRIM      0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_TRIM       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_MODE_CHAN     6
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_PITCH_CHAN    1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_LPF       30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_MODE      1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_ROLL_CHAN     7
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_LPF        30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_MODE       0
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_YAW_CHAN      3
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_YAW_LPF         30
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_YAW_MODE        1
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_D            2
#define JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_D              2
/* Exported types ------------------------------------------------------------*/

/* Exported constants --------------------------------------------------------*/

/* Exported macro ------------------------------------------------------------*/

/* Private variables------------------------------------------------------------------------------*/

/** @brief setting_param_test_for_t3v3
*/
struct _JIG_TEST_setting_param_test_for_t3v3
{
    float value;
    
}JIG_TEST_setting_param_test_for_t3v3[JIG_TEST_NUMBER_OF_PARAM_SETTING] = 
{
    {.value = (float)0},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_P_T3V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_P_T3V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_P_T3V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T3V3_BMI},/// 20
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_IMU_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_T3V3_STIFFNESS_DIR_MOTOR_ROLL},
};

/** @brief setting_param_test_for_s1v3
*/
struct _JIG_TEST_setting_param_test_for_s1v3
{
    float value;
    
}JIG_TEST_setting_param_test_for_s1v3[JIG_TEST_NUMBER_OF_PARAM_SETTING] = 
{
    {.value = (float)0},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_P_S1V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_P_S1V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_P_S1V3 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER_S1V3},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER_S1V3},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_POWER_S1V3},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_S1V3_BMI},/// 20
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_I_S1V3},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_IMU_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_T3V3_STIFFNESS_DIR_MOTOR_ROLL},
};

/** @brief setting_param_test_for_t7
*/
struct _JIG_TEST_setting_param_test_for_t7
{
    float value;
    
}JIG_TEST_setting_param_test_for_t7[JIG_TEST_NUMBER_OF_PARAM_SETTING] = 
{
    {.value = (float)0},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_P_T7 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_P_T7 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_P_T7 + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T7_BMI},/// 20
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_I_T7},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_IMU_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_T3V3_STIFFNESS_DIR_MOTOR_ROLL},
};

/** @brief setting_param_test_for_pixy
*/
struct _JIG_TEST_setting_param_test_for_pixy
{
    float value;
    
}JIG_TEST_setting_param_test_for_pixy[JIG_TEST_NUMBER_OF_PARAM_SETTING] = 
{
    {.value = (float)0},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T7_BMI},/// 20
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_IMU_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE},
};

/** @brief setting_param_test_for_acsl
*/
struct _JIG_TEST_setting_param_test_for_acsl
{
    float value;
    
}JIG_TEST_setting_param_test_for_acsl[JIG_TEST_NUMBER_OF_PARAM_SETTING] = 
{
    {.value = (float)0},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_D},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_YAW},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_NPOLES_PITCH},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_P_PIXY + 1},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ROLL_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_POWER},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_JOY_AXIS},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_LPF_T3V3_BMI},/// 20
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_YAW_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_PITCH_I},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_GYRO_TRUST},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_IMU_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_STATUS_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ORIEN_RATE},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ACSL_ROTATION_TRAVEL_MIN_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_ACSL_ROTATION_TRAVEL_MAX_PIT},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_ROLL},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MIN_PAN},
    {.value = (float)JIG_TEST_SETTING_PARAM_TEST_T3V3_ROTATION_TRAVEL_MAX_PAN},
    
};

/** @brief gimbal_user_profile_ship_T3
*/
struct _JIG_TEST_gimbal_user_profile_ship_T3
{
    float value;
    
}JIG_TEST_gimbal_user_profile_ship_T3[33] = 
{
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_GYRO_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_DIR_MOTOR_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_TILT_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_ROLL_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PAN_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_DIR_MOTOR_PITCH},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_GYRO_TRUST},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_PITCH_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_ROLL_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_YAW_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_RC_YAW_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_PITCH_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T3_YAW_D},
};

/** @brief gimbal_user_profile_ship_AC30000
*/
struct _JIG_TEST_gimbal_user_profile_ship_AC30000
{
    float value;
    
}JIG_TEST_gimbal_user_profile_ship_AC30000[45] = 
{
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MODE_SETTING_ROLL_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MODE_SETTING_JOY_AXIS},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_ROLL_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_GYRO_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_ROLL_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_YAW_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_PITCH_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_STIFFNESS_DIR_MOTOR_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_PITCH_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_PITCH_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_TILT_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_TILT_ROLL_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_YAW_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_YAW_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_PAN_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_FOLLOW_PAN_DIR_MOTOR_PITCH},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_PITCH_SPEED},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_ROLL_SPEED},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_YAW_SPEED},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_PITCH_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_ROLL_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RC_YAW_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_RADIO_TYPE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_HEARTBEAT_EMIT},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_STATUS_RATE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_ENC_CNT_RATE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_ORIEN_RATE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_MSG_RATE_IMU_RATE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CONTROL_ENC_TYPE_SEND},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_IMU_GYRO_TRUST},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_SKIP_GYRO_CALIB},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CAN_LINK_RC_PITCH_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_CAN_LINK_RC_ROLL_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_PIT},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_PIT},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MIN_PAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRAVEL_MAX_PAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_ROTATION_TRIM_HOZ},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_AC30000_MOTOR_ROLL_FOLLOW},
};

/** @brief gimbal_user_profile_ship_s1v3
*/
struct _JIG_TEST_gimbal_user_profile_ship_S1v3
{
    float value;
    
}JIG_TEST_gimbal_user_profile_ship_S1v3[33] = 
{
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_GYRO_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_DIR_MOTOR_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_TILT_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_ROLL_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PAN_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_DIR_MOTOR_PITCH},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_GYRO_TRUST},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_PITCH_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_ROLL_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_YAW_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_RC_YAW_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_PITCH_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_S1V3_YAW_D},
};

/** @brief gimbal_user_profile_ship_T7
*/
struct _JIG_TEST_gimbal_user_profile_ship_T7
{
    float value;
    
}JIG_TEST_gimbal_user_profile_ship_T7[33] = 
{
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_P},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_GYRO_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_POWER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_I},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_DIR_MOTOR_ROLL},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_TILT_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_ROLL_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_FOLLOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_FILTER},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PAN_WINDOW},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_DIR_MOTOR_PITCH},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_GYRO_TRUST},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_TRIM},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_MODE_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_PITCH_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_PITCH_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_ROLL_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_ROLL_MODE},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_SBUS_YAW_CHAN},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_RC_YAW_LPF},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_D },
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_PITCH_D},
    {.value = (float)JIG_TEST_GIMBAL_USER_PROFILE_SHIP_T7_YAW_D},
};
/* Exported functions --------------------------------------------------------*/

#ifdef __cplusplus
}
#endif

#endif /* __JIG_TEST_PARAM_GIMBAL_H */

/************************ (C) COPYRIGHT GREMSY *****END OF FILE****************/

